### ISSUE TITLE
Star value not reflecting passed in value

### ISSUE THREAD

**Issue by evanbechtol** [StartPolymer/s-rating#1]
I am noticing that sometimes, the component does not show the highlighted number of stars, which reflect the value passed in.

```
<template is="dom-repeat" items="[[sus.feedback]]">
     <li>
         <s-rating value="[[item.rating]]" disabled></s-rating>
         <em style="margin-left: 10px;">([[item.rating]]) :"[[item.remarks]]" -[[item.user]]</em>
     </li>
</template>
```
In the image below, the number in parenthesis is the number being passed into the component.
![image](https://user-images.githubusercontent.com/10092035/29371973-7d7961e0-826f-11e7-9d65-80bb54db94e3.png)

**Comment by BadCash** [comment]
I'm having the same issue. Sort of defeats the whole purpose of the component...
